### ISSUE TITLE
Diferenças de versões

### ISSUE THREAD

**Issue by ajunior** [chcandido/brModelo#2]
A versão de desenvolvimento tem numeração diferente da apresentada na aplicação.
Atualmente, pelo que percebi, a versão de desenvolvimento é a 3.20, enquanto a versão apresentada na aplicação é a 3.3.3. Na aplicação também tem a informação da versão do Diagrama, que aparentemente condiz com a versão de desenvolvimento. Isso causa uma certa confusão nos usuários, então seria interessante esclarecer isso.

![screenshot 42](https://user-images.githubusercontent.com/398263/50634587-f16e6680-0f2d-11e9-818a-bc0fe0cb2368.png)

BTW: A aplicação está cada vez melhor. Parabéns!

**Comment by chcandido** [comment]
Entendi.
Verei o que está diferente e corrigirei. Obrigado.


Carlos H. Cândido

________________________________
De: Adjamilton Junior <notifications@github.com>
Enviado: Thursday, January 3, 2019 8:03:35 AM
Para: chcandido/brModelo
Cc: Subscribed
Assunto: [chcandido/brModelo] Diferenças de versões (#2)


A versão de desenvolvimento tem numeração diferente da apresentava na aplicação.
Atualmente, pelo que percebi, a versão de desenvolvimento é a 3.20, enquanto a versão apresentada na aplicação é a 3.3.3. Na aplicação também tem a informação da versão do Diagrama, que aparentemente condiz com a versão de desenvolvimento. Isso causa uma certa confusão nos usuários, então seria interessante esclarecer isso.

[screenshot 42]<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F398263%2F50634587-f16e6680-0f2d-11e9-818a-bc0fe0cb2368.png&data=02%7C01%7C%7C9d9b670cf0ce49377d2f08d6716b1bf7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636821102170058866&sdata=%2BNB01OugG3QcygIjcr7rLe24Dg4mLy3wBnndZzaV2k4%3D&reserved=0>

BTW: A aplicação está cada vez melhor. Parabéns!
