### ISSUE TITLE
Tema claro sem alterar o tema do sistema Ubuntu

### ISSUE THREAD

**Issue by Vini-Pires** [chcandido/brModelo#29]
Olá, Devs!

Recentemente, comecei a usar o brModelo para minhas aulas na faculdade. No entanto, como utilizo o Linux, o tema do aplicativo fica sempre fixo ao tema padrão do sistema. Gostaria de saber se existe alguma maneira de usar o brModelo com o tema claro sem precisar alterar o tema do meu sistema operacional.

**Comment by Vini-Pires** [comment]
Resolvi esse problema através do gnome tweak tools seguindo esses passos para o ubuntu 23.10

**Passo 1**: Instalar o Gnome Tweak Tools

1. Abra o terminal e digite o seguinte comando:
    - `sudo apt install gnome-tweaks`

**Passo 2**: Acessar as configurações de tema

1. Abra o Gnome Tweak Tools.
1. Na barra lateral, selecione "Aparência".

**Passo 3**: Mudar para o tema claro

1. Na seção "Aplicativos legado", localize a opção "Cor".
1. No menu suspenso, selecione "Claro".

**Passo 4**: Reiniciar o computador

1. Para que as alterações sejam aplicadas, reinicie o computador. (Não foi necessario para mim, mas recomendo ainda assim)

> Resolvido essa issue irei feche-la após esse comentário. Boa sorte aqueles que tiverem o mesmo problema

**Comment by chcandido** [comment]
Resolvido.
________________________________
De: Vinícius Pires ***@***.***>
Enviado: segunda-feira, 8 de abril de 2024 16:54
Para: chcandido/brModelo ***@***.***>
Cc: Subscribed ***@***.***>
Assunto: Re: [chcandido/brModelo] Tema claro sem alterar o tema do sistema Ubuntu (Issue #29)


Resolvi esse problema através do gnome tweak tools seguindo esses passos para o ubuntu 23.10

Passo 1: Instalar o Gnome Tweak Tools

  1.  Abra o terminal e digite o seguinte comando:
     *   sudo apt install gnome-tweaks

Passo 2: Acessar as configurações de tema

  1.  Abra o Gnome Tweak Tools.
  2.  Na barra lateral, selecione "Aparência".

Passo 3: Mudar para o tema claro

  1.  Na seção "Aplicativos legado", localize a opção "Cor".
  2.  No menu suspenso, selecione "Claro".

Passo 4: Reiniciar o computador

  1.  Para que as alterações sejam aplicadas, reinicie o computador. (Não foi necessario para mim, mas recomendo ainda assim)

Resolvido essa issue irei feche-la após esse comentário. Boa sorte aqueles que tiverem o mesmo problema
