### ISSUE TITLE
new features / correções

### ISSUE THREAD

**Issue by mateusjunges** [chcandido/brModelo#5]
## Feature
- Adicionar ferramentas de zoom in e zoom out
-Manter a ferramenta para adicionar atributos selecionada. Se preciso adicionar mais de um atributo preciso clicar duas vezes para selecioná-la toda vez, o que deixa o trabalho nada produtivo, além de estressante.

## Correção
- Erro ao adicionar atributo a relação (Access violation address in module brModelo.exe)

**Comment by chcandido** [comment]
Sugiro que você experimente a versão mais recente da ferramenta!
BrModelo.jar

www.sis4.com
________________________________
De: Mateus Junges <notifications@github.com>
Enviado: domingo, 7 de abril de 2019 12:59
Para: chcandido/brModelo
Cc: Subscribed
Assunto: [chcandido/brModelo] new features / correções (#5)

Feature

  *   Adicionar ferramentas de zoom in e zoom out
-Manter a ferramenta para adicionar atributos selecionada. Se preciso adicionar mais de um atributo preciso clicar duas vezes para selecioná-la toda vez, o que deixa o trabalho nada produtivo, além de estressante.

Correção

  *   Erro ao adicionar atributo a relação (Access violation address in module brModelo.exe)

**Comment by bastostuliojrrt** [comment]
Link fora do ar

**Comment by chcandido** [comment]
Reestabelecido.
Muito obrigado pelo aviso!

Carlos H. Cândido.
________________________________
De: bastostuliojrrt ***@***.***>
Enviado: quinta-feira, 24 de junho de 2021 19:01
Para: chcandido/brModelo ***@***.***>
Cc: Carlos Henrique Candido ***@***.***>; Comment ***@***.***>
Assunto: Re: [chcandido/brModelo] new features / correções (#5)


Link fora do ar
